# version: '3'
services:
  # Teedy Application
  teedy-server:
    #image: sismics/docs:v1.11
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # Base URL for the application
      DOCS_BASE_URL: "http://localhost:8080"
      # Admin Credentials
      DOCS_ADMIN_EMAIL_INIT: "admin@example.com"
      DOCS_ADMIN_PASSWORD_INIT: "$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS"
      # Connect to PostgreSQL running on the host machine
      DATABASE_URL: "jdbc:postgresql://host.docker.internal:5432/boveda_db"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "admin"
      DATABASE_POOL_SIZE: "10"
    volumes:
      - ./docs/data:/data
    networks:
      - internet
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  internet:
    driver: bridge
